# Funções aritméticas: multiplicação

In [2]:
import numpy as np

In [3]:
# multiplicações elemento a elemento
x = np.ones((2,2))
y = np.eye(2)
print('x:\n',x)
print('y:\n',y)

x:
 [[1. 1.]
 [1. 1.]]
y:
 [[1. 0.]
 [0. 1.]]


In [6]:
# multiplicação
print('multiplicação de dois arrays:\n', x * y)
print('multiplicação com float/int:\n', x*2)

multiplicação de dois arrays:
 [[1. 0.]
 [0. 1.]]
multiplicação com float/int:
 [[2. 2.]
 [2. 2.]]


In [7]:
# multiplicação matricial
print('multiplicação matricial (np.dot):\n',np.dot(x,y))
print('multiplicação matricial (@):\n ', x @ y)
print('multiplicação matricial (.dot):\n ', x.dot(y))

multiplicação matricial (np.dot):
 [[1. 1.]
 [1. 1.]]
multiplicação matricial (@):
  [[1. 1.]
 [1. 1.]]
multiplicação matricial (.dot):
  [[1. 1.]
 [1. 1.]]


## Solução de sistemas

In [19]:
""" 
Exemplo:
Solução de um sistema de equações:
a + 2*b = 7
3a + 2*b = -11
    solução analítica: (a,b) = (-1,4)
Matricialmente, este problema tem a seguinte forma:
Ax = C, onde
- x = [a,b]
- A = [[1,2],[3,2]]
- C = [7,-11]
solução numérica: x = inv(A) @ C,
"""

# definição do problema
A = np.array([[1,2],[3,2]])
C = np.array([[7],[-11]])
print('A:\n',A)
print('C:\n',C)


A:
 [[1 2]
 [3 2]]
C:
 [[  7]
 [-11]]


In [21]:
# solução

# x = np.dot(np.linalg.inv(A),C)
x = np.linalg.inv(A) @ C
print('(a,b)',x.ravel())

(a,b) [-9.  8.]
