# Numpy

In [3]:
import numpy as np

## Criação de arrays

In [ ]:
help(np.array)

In [5]:
# criação de um array 1D: [1,2,3]
l = [1,2,3]
x = np.array(l)
print('x:',x)
print('shape:',x.shape)  

x: [1 2 3]
shape: (3,)


In [6]:
type(x)

numpy.ndarray

In [7]:
# criação de um array 2D: linhas aninhadas
l = [[1,2],[3,4]]
x = np.array(l)
print('x:',x)
print('shape:',x.shape)  


x: [[1 2]
 [3 4]]
shape: (2, 2)


In [8]:
type(x)


numpy.ndarray

In [ ]:
help(np.zeros)

In [17]:
# array contendo apenas ZEROS
dim = (3,3) # (linhas,colunas)
x = np.zeros(dim)
print('x:\n',x)
print('shape:',x.shape)  

x:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
shape: (3, 3)


In [18]:
# array contendo apenas UNS
size = (2,2) # (linhas,colunas)
x = np.ones(size)
print('x:\n',x)
print('shape:',x.shape)  

x:
 [[1. 1.]
 [1. 1.]]
shape: (2, 2)


In [ ]:
# np.linspace?

In [21]:
# criação de valores dentro de um intervalo
# valores uniformes entre 5 e 15
x_min,x_max = 5,15
x = np.linspace(x_min,x_max,num=6)
print('x:\n',x)
print('shape:',x.shape)  

x:
 [ 5.  7.  9. 11. 13. 15.]
shape: (6,)


In [22]:
# criação de uma matriz identidade
n = 4
x = np.eye(n)
print('x:\n',x)
print('shape:',x.shape) 

x:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
shape: (4, 4)


In [23]:
# criação de valores aleatórios
# np.random.seed(10)

x = np.random.random(size=(2,3))
print('x:\n',x)
print('shape:',x.shape) 


x:
 [[0.93580292 0.00820154 0.84481465]
 [0.02041722 0.96996738 0.12916315]]
shape: (2, 3)
