# Indexação de arrays

In [1]:
import numpy as np

In [4]:
# os indices no Python vão de 0 a n-1
# onde n é o tamanho da dimensão

x = np.linspace(start=10,stop=100,num=10)
print('x:\n',x)
print('shape:',x.shape)  

x:
 [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
shape: (10,)


In [7]:
# extração de elementos
print('x:',x)
print('primeiro elemento:',x[0])
print('segundo elemento:',x[1])
print('último elemento:',x[9])
print('último elemento:',x[-1])

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
primeiro elemento: 10.0
segundo elemento: 20.0
último elemento: 100.0
último elemento: 100.0


In [13]:
# slacing: extração de subarray:
print('x:',x)
print('dois primeiros elementos:',x[0:2])
print('dois primeiros elementos:',x[:2])
print('dois últimos elementos:',x[-2:])
print('dois últimos elementos:',x[8:])


x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
dois primeiros elementos: [10. 20.]
dois primeiros elementos: [10. 20.]
dois últimos elementos: [ 90. 100.]
dois últimos elementos: [ 90. 100.]


In [15]:
# slicing em arrays 2D (matrizes)
x = x.reshape(2,5)
print('x:\n',x)


x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]


In [17]:
# extraçãp de elemtos
print('primeira linha, segunda coluna',x[0,1])
print('segunda linha, penúltima coluna',x[1,-2])
print('última linha, última coluna',x[-1,-1])
print('última linha, última coluna',x[1,4])

primeira linha, segunda coluna 20.0
segunda linha, penúltima coluna 90.0
última linha, última coluna 100.0
última linha, última coluna 100.0


In [23]:
# slicing: extração de subarrays
print('x:\n',x)
print('primeira linha inteira',x[0, :])
print('primeira linha, segunda a quarta coluna',x[0,1:4])
print('última coluna inteira\n',x[:,[-1]])


x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]
primeira linha inteira [10. 20. 30. 40. 50.]
primeira linha, segunda a quarta coluna [20. 30. 40.]
última coluna inteira
 [[ 50.]
 [100.]]


# SLICE COMPARTILHA A MEMÓRIA DO ARRAY ORIGINAL

## EXEMPLO

In [25]:
# atenção com o compartilhamento de memória em subarrays!
x = np.array([1,2,3])
print('x:\n',x)
y = x[:2]
y[0] = -100 # alteração do valor em y altera o valor de x
print(x)


x:
 [1 2 3]
[-100    2    3]


# PARA EVITAR O VALOR DO ARRAY PRINCIPAL DEVEMOS UTILIZAR O MÉTODO COPY


In [26]:
# atenção com o compartilhamento de memória em subarrays!
x = np.array([1,2,3])
print('x:\n',x)
y = x[:2].copy()
y[0] = -100 # não altera mais o valor de x
print(x)

x:
 [1 2 3]
[1 2 3]
